[package]
name = "mnist_nn"
version = "0.1.0"
# cairo-version = "2.1.0-rc0"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", branch = "einsum-impl" }

[scripts]
test = "scarb cairo-test -f mnist_nn_test"